- name: Bootstrap development environment (Ubuntu)
  hosts: localhost

  tasks:
    - name: Update apt and install required system packages
      become: true
      apt:
        pkg:
          - git
          - tmux
          - curl
          - wget
          - zsh
          - rsync
          - git-lfs
          - vim
          - openssl
          - make
          - software-properties-common
          - texlive
          - texlive-latex-extra
          - texlive-fonts-extra
          - texlive-science
          - latexmk
          - xclip
          - biber
          - xdotool
          - ca-certificates
          - gnupg
          - build-essential
          - unzip
          - python3-dev
          - python3-pip
          - apt-utils
          - openssh-client
          - gnupg2
          - dirmngr
          - iproute2
          - procps
          - lsof
          - htop
          - net-tools
          - psmisc
          - ca-certificates
          - unzip
          - zip
          - nano
          - vim-tiny
          - less
          - jq
          - lsb-release
          - apt-transport-https
          - dialog
          - libc6
          - libgcc1
          - libkrb5-3
          - libgssapi-krb5-2
          - libicu[0-9][0-9]
          - liblttng-ust[0-9]
          - libstdc++6
          - zlib1g
          - locales
          - sudo
          - ncdu
          - man-db
          - strace
          - manpages
          - manpages-dev
          - stow
          - zathura
        state: latest
        update_cache: true
      tags:
        - packages

    - name: Install Python packages
      shell: python3 -m pip install requests
      tags:
        - python

    - name: Get the path to ZSH
      become: false
      local_action: command which zsh
      register: zsh_path
      tags:
        - packages

    - name: Install Oh My ZSH
      shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
      args:
        creates: /home/dadalto/.oh-my-zsh
      tags:
        - packages

    - name: Set ZSH as the default shell
      shell: chsh -s $(which zsh) root
      become: true
      tags:
        - packages

    - name: Setup zsh plugins (autosuggestions)
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: /home/dadalto/.oh-my-zsh/plugins/zsh-autosuggestions
        version: master
        accept_hostkey: yes
      tags:
        - configuration

    - name: Setup zsh plugins (synthax  highlighting)
      git:
        repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
        dest: /home/dadalto/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting
        version: master
        accept_hostkey: yes
      tags:
        - configuration

    - name: Install neovim 0.8.0+
      become: true
      shell: |
        add-apt-repository ppa:neovim-ppa/unstable -y
        apt update -y
        apt install neovim -y

    - name: Install Lazygit
      shell: |
        LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | grep -Po '"tag_name": "v\K[^"]*') && \
        curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
        tar xf lazygit.tar.gz lazygit
        install lazygit /usr/local/bin
        rm -r lazygit.tar.gz

    - name: Install LunarVim
      shell: |
        curl https://raw.githubusercontent.com/lunarvim/lunarvim/master/utils/installer/install.sh > /tmp/install.sh
        echo $PATH
        echo $HOME
        bash /tmp/install.sh -y
        /home/dadalto/.local/bin/lvim --headless "+Lazy! sync" +qa

    - name: Install node and npm
      become: true
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
        NODE_MAJOR=20  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
        apt update
        apt install nodejs

    - name: Install protoc
      shell: echo "TODO v0.14.2 GO111MODULE=on go install golang.org/x/tools/gopls@v0.14.2"
